service: thesmallestrailsapp
image: artemave/thesmallestrailsapp

servers:
  web:
    - 23.88.36.68

proxy:
  ssl: true
  host: thesmallestrailsapp.dev
  healthcheck:
    path: /
    interval: 3
    timeout: 5

registry:
  server: ghcr.io
  username: artemave
  password:
    - KAMAL_REGISTRY_PASSWORD

builder:
  arch: amd64
